version: "3.9"

services:
  risa_ai:
    container_name: "risa_ai"
    image: ghcr.io/martokk/risa_ai:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/risa_ai/data:/risa_ai/data
      - ./app:/app
    ports:
      - "5000:5000"
    user: "${UID}:${GID}"
