version: "3.9"

services:
  risa:
    container_name: "risa"
    image: "risa"
    build:
      context: .
      # context: https://github.com/martokk/risa.git#main
      target: production
    restart: unless-stopped
    # depends_on:
    #   - duckdns
    # env_file:
    #   # - /home/ubuntu/volumes/risa/.env
    #   - ./risa/.env
    volumes:
      # - /home/ubuntu/volumes/risa/.env:/workspace/.env
      # - /home/ubuntu/volumes/risa/media:/workspace/media
      # - /home/ubuntu/volumes/risa/logs:/workspace/logs
      # - /home/ubuntu/volumes/risa/db.sqlite3:/workspace/db.sqlite3
      - ./risa/config:/risa/config
      - ./risa/data:/risa/data
    ports:
      - "8003:8003"
