version: "3.9"

services:
  risa:
    container_name: "risa"
    image: ghcr.io/martokk/risa:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/risa/data:/risa/data
      - ./app:/app
    ports:
      - "5000:5000"
    user: "${UID}:${GID}"
