"""added RUNPOD_TCP_PORT_22

Revision ID: 06e2a61f1f06
Revises: c652377f0799
Create Date: 2025-07-04 22:37:17.462824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '06e2a61f1f06'
down_revision = 'c652377f0799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instancestate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runpod_tcp_port_22', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instancestate', schema=None) as batch_op:
        batch_op.drop_column('runpod_tcp_port_22')

    # ### end Alembic commands ###
