"""updated character.person_name

Revision ID: 1ab37aca2a4c
Revises: e4cf96f84b8d
Create Date: 2025-05-29 16:42:43.286816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1ab37aca2a4c'
down_revision = 'e4cf96f84b8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
