"""added job table

Revision ID: 9b4bd6cb617a
Revises: 876fb6a92064
Create Date: 2025-06-17 16:10:56.082387

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '9b4bd6cb617a'
down_revision = '876fb6a92064'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('env_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('command', 'api_post', name='jobtype'), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('highest', 'high', 'normal', 'low', 'lowest', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'failed', 'done', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_id'))

    op.drop_table('job')
    # ### end Alembic commands ###
