"""fixing sd_extra_network

Revision ID: a4e5eddc5ef7
Revises: c72b67c15bad
Create Date: 2025-06-06 22:15:09.366198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a4e5eddc5ef7'
down_revision = 'c72b67c15bad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trained_on_checkpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('network_trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('network_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.drop_column('sha256')
        batch_op.drop_column('network_weight')
        batch_op.drop_column('network_trigger')
        batch_op.drop_column('network')
        batch_op.drop_column('trained_on_checkpoint')

    # ### end Alembic commands ###
