"""updated job types

Revision ID: b849ef49bbf0
Revises: d25d4f326813
Create Date: 2025-06-28 01:19:47.889165

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b849ef49bbf0'
down_revision = 'd25d4f326813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE jobtype ADD VALUE 'script'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
