"""added lora_path

Revision ID: bba3c04d129f
Revises: 1ab37aca2a4c
Create Date: 2025-05-29 17:46:41.589687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'bba3c04d129f'
down_revision = '1ab37aca2a4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.drop_column('local_file_path')

    # ### end Alembic commands ###
