"""init

Revision ID: c1f57b925140
Revises: 
Create Date: 2025-05-21 19:28:57.858262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c1f57b925140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skin_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hair_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hair_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hair_length', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('face_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('eye_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('makeup_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('breasts_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('breasts_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nipples_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hands_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hips_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ass_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pussy_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('legs_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feet_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clothing_head', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clothing_upper_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clothing_lower_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clothing_feet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sdbasemodel',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sdcheckpoint',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_realistic', sa.Boolean(), nullable=False),
    sa.Column('sd_base_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sd_base_model_id'], ['sdbasemodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sdextranetwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sd_base_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lora_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('only_realistic', sa.Boolean(), nullable=False),
    sa.Column('only_nonrealistic', sa.Boolean(), nullable=False),
    sa.Column('only_checkpoints', sa.JSON(), nullable=True),
    sa.Column('exclude_checkpoints', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['sd_base_model_id'], ['sdbasemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sdextranetwork_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sdextranetwork_id'))

    op.drop_table('sdextranetwork')
    op.drop_table('sdcheckpoint')
    op.drop_table('sdbasemodel')
    op.drop_table('character')
    # ### end Alembic commands ###
