"""added dual pipe job queue

Revision ID: c652377f0799
Revises: 278bd29c355d
Create Date: 2025-07-03 11:28:47.921373

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c652377f0799'
down_revision = '278bd29c355d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='default'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('queue_name')

    # ### end Alembic commands ###
