"""added local/remote paths2

Revision ID: c72b67c15bad
Revises: fbbf6d226b7a
Create Date: 2025-06-01 17:55:16.048937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c72b67c15bad'
down_revision = 'fbbf6d226b7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.drop_column('local_file_path')

    # ### end Alembic commands ###
