"""renamed local_file_path to hub_file_path

Revision ID: cb8b064105b1
Revises: 21887c304c0e
Create Date: 2025-07-02 12:38:56.633573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'cb8b064105b1'
down_revision = '21887c304c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdcheckpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hub_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Copy data from local_file_path to hub_file_path
    op.execute("UPDATE sdcheckpoint SET hub_file_path = local_file_path")
    with op.batch_alter_table('sdcheckpoint', schema=None) as batch_op:
        batch_op.drop_column('local_file_path')

    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hub_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Copy data from local_file_path to hub_file_path
    op.execute("UPDATE sdextranetwork SET hub_file_path = local_file_path")
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.drop_column('local_file_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('hub_file_path')

    with op.batch_alter_table('sdcheckpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('hub_file_path')

    # ### end Alembic commands ###
