"""added character.character_names

Revision ID: e4cf96f84b8d
Revises: 4f3933104771
Create Date: 2025-05-29 14:43:06.692528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e4cf96f84b8d'
down_revision = '4f3933104771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('character_name1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('character_name2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('character_name3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Migrate data from name to person_name
    op.execute('UPDATE character SET person_name = name')
    
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))

    # Migrate data back from person_name to name    
    op.execute('UPDATE character SET name = person_name')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('character_name3')
        batch_op.drop_column('character_name2')
        batch_op.drop_column('character_name1')
        batch_op.drop_column('person_name')

    # ### end Alembic commands ###
