"""fixing sd_extra_network2

Revision ID: eee77d4b01af
Revises: a4e5eddc5ef7
Create Date: 2025-06-06 22:28:02.387106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'eee77d4b01af'
down_revision = 'a4e5eddc5ef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.drop_column('lora_sha256')
        batch_op.drop_column('lora_tag')
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdextranetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('lora_tag', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('lora_sha256', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
