"""updated job types 2

Revision ID: f20c9dced3eb
Revises: b849ef49bbf0
Create Date: 2025-06-29 14:48:58.012306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f20c9dced3eb'
down_revision = 'b849ef49bbf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE jobstatus ADD VALUE 'error'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
