"""added local/remote paths

Revision ID: fbbf6d226b7a
Revises: bba3c04d129f
Create Date: 2025-06-01 17:36:35.545312

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'fbbf6d226b7a'
down_revision = 'bba3c04d129f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdcheckpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('sdcheckpoint', schema=None) as batch_op:
        batch_op.drop_column('remote_file_path')
        
    # ### end Alembic commands ###
